### ISSUE TITLE
There is maybe a mistake in the wiki.

### ISSUE THREAD

**Issue by muratbozkurt35** [vorov2/dyalect#341]
![image](https://user-images.githubusercontent.com/62115850/87778678-3ddd7680-c834-11ea-9f99-827a8a92cfaf.png)

in the page [Standard Operators](https://github.com/vorov2/dyalect/wiki/Standard-operators), i guess there is a mistake.
Shouldn't there be set instead of get in the last line of last code example in that page?

**Comment by vorov2** [comment]
Yes, this is a typo. Thanks for noting.
Fixed now.

**Comment by muratbozkurt35** [comment]
Thanks for noting.
> Fixed now.



> Thanks for noting.
die alone incel.
