### ISSUE TITLE
"Reassign" keywords

### ISSUE THREAD

**Issue by Marty-Stu** [vorov2/dyalect#957]
I would really like to be able to `"reassign" keywords` in such a way that I can write like this:
```fs
let tup = 1, 2, 3

let   res
    = match tup
      | 1, x      ->  x
      | 1, x, 4   ->  x * 4
      | 1, x, 3   ->  x * 3
      | _         ->  0
```
or
```fs
let   res
    = match   tup
       with | 1, x      ->  x
            | 1, x, 4   ->  x * 4
            | 1, x, 3   ->  x * 3
            | _         ->  0
```
instead of such an entry:
```dy
let tup = (1, 2, 3)

let   res
    = match tup
      {
        (1, x)      =>  x,
        (1, x, 4)   =>  x * 4,
        (1, x, 3)   =>  x * 3,
        _           =>  0
      }
```

Just `"reassign"` strings:
- `"=>" ` <-> `"->"`
- `","  ` <-> `"|"`
- `{...}` <-> `space indentation`
- `(...)` <-> `brackets are optional`

It's just that it's more convenient to read the code without being distracted by `"punctuation"` (more concise).

Also would love to have `"meta-match"` (`Active Patterns` in F#):
```fs
let   (|Odd|Even|)
      x
    = if      x % 2 = 0
        then  Even x
        else  Odd  x

let   f x
    = match   x
      | Odd   odd   ->  printfn $"odd  : %i{odd}"
      | Even  even  ->  printfn $"even : %i{even}"
```
or
```fs
let   f x
    = match   x
       with | Odd  odd   ->  printfn $"odd  : %i{odd}"
            | Even even  ->  printfn $"even : %i{even}"
```

`PS:` Please blame `Google Translate` for the clumsiness of the written :)

**Comment by vorov2** [comment]
Reassigning is not something that can be supported with the current parser infrastructure/operator threatment. Also the syntax that you are proposing is ML/F# syntax which looks quite different from the rest of the language which implements a modern take on the C style syntax (like Go or Swift) and is not indentation based.

**Comment by vorov2** [comment]
As for active pattern I can't really say that I have a good vision of "usefulness" of this feature. It is possible to implement, but you can write pretty similar code right now without any additional language constructs:

```swift
func evenOdd(x) {
    if x % 2 == 0 {
        @Even(x)
    } else {
        @Odd(x)
    }
}

match evenOdd(42) {
    @Even(x) => print("Even \(x)"),
    @Odd(x) => print("Odd \(x)")
}
```

Maybe I am missing something here...

**Comment by Marty-Stu** [comment]
> Reassigning is not something that can be supported with the current parser infrastructure/operator threatment. Also the syntax that you are proposing is ML/F# syntax which looks quite different from the rest of the language which implements a modern take on the C style syntax (like Go or Swift) and is not indentation based.

I see. Thanks.
